from pydantic import BaseModel
from typing import Optional
from enum import Enum


class AgentMode(str, Enum):
    EVALUATOR = "evaluator"
    TEACHER = "teacher"


class Message(BaseModel):
    role: str
    content: str


class StudentProfile(BaseModel):
    """Profile generated by Evaluator, used by Teacher"""
    comprehension_score: int  # 0-100
    fundamentals_score: int   # 0-100
    understanding_score: int  # 0-100
    interest_score: int       # 0-100
    
    reading_level: str        # "beginner", "intermediate", "advanced"
    interests: list[str]      # Topics they enjoy
    weak_areas: list[str]     # Areas to focus on
    strong_areas: list[str]   # Areas they excel in


class EvaluationPlan(BaseModel):
    """Plan created by Evaluator for Teacher to follow"""
    student_profile: StudentProfile
    recommended_difficulty: str  # "easy", "medium", "hard"
    focus_areas: list[str]       # What Teacher should emphasize
    suggested_topics: list[str]  # Topics to explore
    teaching_style: str          # "encouraging", "challenging", "detailed"


class ChatRequest(BaseModel):
    messages: list[Message]
    mode: AgentMode = AgentMode.EVALUATOR
    evaluation_stage: Optional[str] = None
    answers: list[str] = []
    evaluation_plan: Optional[EvaluationPlan] = None


class ChatResponse(BaseModel):
    content: str
    mode: AgentMode
    evaluation_complete: bool = False
    evaluation_plan: Optional[EvaluationPlan] = None
